# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QLineEdit

# -----------CHEMI KODI-------------------------------CHEMI KODI-------------------------------CHEMI KODI---------------------
cur_username = ''
cur_password = ''
my_username = 'Tsarevich25'
my_passworc = '1234567890g'

# -----------CHEMI KODI-------------------------------CHEMI KODI-------------------------------CHEMI KODI---------------------






class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 334)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 0, 411, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 351, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.redister_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.redister_button.setFont(font)
        self.redister_button.setObjectName("redister_button")
        self.horizontalLayout.addWidget(self.redister_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 80, 351, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.username_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_value.setFont(font)
        self.username_value.setObjectName("username_value")
        self.verticalLayout_2.addWidget(self.username_value)
        #mycode
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_value.setFont(font)
        self.password_value.setObjectName("password_value")
        self.horizontalLayout_2.addWidget(self.password_value)
        self.show_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.show_button.setObjectName("show_button")
        self.horizontalLayout_2.addWidget(self.show_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        #mycode
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.enter_button = QtWidgets.QPushButton(self.page_2)
        self.enter_button.setGeometry(QtCore.QRect(110, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enter_button.setFont(font)
        self.enter_button.setObjectName("enter_button")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        #-----------CHEMI KODI-------------------------------CHEMI KODI-------------------------------CHEMI KODI---------------------
        self.login_button.clicked.connect(self.login_page)
        self.enter_button.clicked.connect(self.enter_action)
        self.password_value.setEchoMode(QLineEdit.Password)
        self.show_button.setCheckable(True)
        self.show_button.clicked.connect(self.show_password)
        self.username_value.setPlaceholderText("username")
        self.password_value.setPlaceholderText("password")

        self.message_box = QMessageBox()
        self.message_box.setIcon(QMessageBox.Warning)




    def show_password(self):
        if self.show_button.isChecked():
            self.password_value.setEchoMode(QLineEdit.Normal)
        else:
            self.password_value.setEchoMode(QLineEdit.Password)


    def enter_action(self):
        cur_username = self.username_value.text()
        cur_password = self.password_value.text()
        if my_username == cur_username and my_passworc == cur_password:
            self.stackedWidget.setCurrentIndex(2)
        else:
            self.message_box.setText("username and password are not correct, please try again")
            self.message_box.show()
            self.password_value.setText('')
            self.username_value.setText('')


        print(cur_password, cur_username)

    def login_page(self):
        self.stackedWidget.setCurrentIndex(1)

    # -------------CHEMI KODI----------------------------CHEMI KODI-------------------------------CHEMI KODI---------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "            MY FIRST APPLICATION"))
        self.login_button.setText(_translate("MainWindow", "LOG IN"))
        self.redister_button.setText(_translate("MainWindow", "REGISTER"))
        self.label_3.setText(_translate("MainWindow", "            MY FIRST APPLICATION"))
        self.show_button.setText(_translate("MainWindow", "show"))
        self.enter_button.setText(_translate("MainWindow", "LOG IN"))
        self.label_2.setText(_translate("MainWindow", "       welcome back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
